### ISSUE TITLE
Contracts not getting mapped to epgs

### ISSUE THREAD

**Issue by jorgenspange** [terraform-cisco-modules/easy-aci#1]
Greetings!

Seems like there's something causing contracts not to get mapped to epgs.
Here's my code:

Contract config:
````yaml
        - contract_type: standard
          description: Contract for management traffic towards l3out
          name: company-mgt:l3out-ct
          subjects:
            - action: permit
              apply_both_directions: true
              filters:
                - "any"
              name: company_mgt_l3out_fltr
      filters:
        - description: default
          filter_entries:
            - description: default
              name: default
              stateful: false
          name: any

````
And here's my epg:

````yaml
          external_epgs:
            - name: company_mgt_l3out_ext_epg
              contracts:
                - name: company-mgt:l3out-ct
                  contract_type: provided
````

Best regards

**Comment by scotttyso** [comment]
@jorgenspange , interesting.  I am not sure without testing what the root cause is.. I am out of office right now but will look later next week when I am back in the office.

**Comment by scotttyso** [comment]
@jorgenspange 

What version of the module are you using?  I just tested with 3.0.4 and it applied the contract to the External EPG

```yaml
      l3outs:
      - description: Asgard Production L3Out
        enable_bgp: true
        external_epgs:
        - contracts:
          - contract_type: consumed
            name: testing_123
          - contract_type: provided
            name: testing_123
          description: Asgard Prod
          name: prod
          preferred_group_member: true
          subnets:
          - external_epg_classification:
              external_subnets_for_external_epg: true
            subnets:
            - 0.0.0.0/1
            - 128.0.0.0/1
```


```terraform
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"] will be created
  + resource "aci_rest_managed" "external_epg_contracts" {
      + class_name = "fvRsProv"
      + content    = {
          + "prio"         = "unspecified"
          + "tnVzBrCPName" = "testing_123"
        }
      + dn         = "uni/tn-common/out-asgard-prod/instP-prod/rsprov-testing_123"
      + id         = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```terraform
tyscott@TYSCOTT-DESKTOP:~/terraform-cisco-modules/easy-aci/RICH/TEST$ tfa
module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"]: Creating...
module.built_in_tenants["common"].aci_rest_managed.external_epg_contracts["asgard-prod:prod:provided:testing_123"]: Creation complete after 0s [id=uni/tn-common/out-asgard-prod/instP-prod/rsprov-testing_123]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:
```

I am looking for what is configured in the main.tf under the built_in_tenants and tenants modules:

```terraform
module "built_in_tenants" {
  depends_on = [module.access]
  # source     = "../../../terraform-aci-tenants"
  source  = "terraform-cisco-modules/tenants/aci"
  version = "3.0.4"
  for_each = {
    for v in lookup(local.model, "tenants", []) : v.name => v if length(regexall("^(common|infra|mgmt)$", v.name)) > 0
  }
  model = merge(each.value, lookup(local.model, "templates", {}), {
    aaep_to_epgs    = {}
    global_settings = local.global_settings
    switch          = {}
    templates       = lookup(local.model, "templates", {})
  })
  tenant           = each.key
  tenant_sensitive = local.tenant_sensitive
}
```

```terraform
module "tenants" {
  depends_on = [module.built_in_tenants]
  #source     = "../../../terraform-aci-tenants"
  source  = "terraform-cisco-modules/tenants/aci"
  version = "3.0.4"
  for_each = {
    for v in lookup(local.model, "tenants", []) : v.name => v if length(regexall("^(common|infra|mgmt)$", v.name)) == 0
  }
  model = merge(each.value, lookup(local.model, "templates", {}), {
    aaep_to_epgs    = {}
    global_settings = local.global_settings
    switch          = {}
    templates       = lookup(local.model, "templates", {})
  })
  tenant           = each.key
  tenant_sensitive = local.tenant_sensitive
}
```
